import subprocess
from pathlib import Path


def deploy_to_ollama(model_name: str, gguf_path: str | Path) -> None:
    """Deploy a GGUF model to Ollama locally.

    Generates a Modelfile and registers it with the Ollama daemon.

    Args:
        model_name: Name of the model in Ollama.
        gguf_path: Path to the GGUF file.
    """
    gguf_path = Path(gguf_path)
    if not gguf_path.exists():
        raise FileNotFoundError(f"GGUF file not found: {gguf_path}")

    modelfile_path = gguf_path.parent / "Modelfile"

    modelfile_content = f"""FROM {gguf_path.absolute()}

# Auto-generated by Forge
TEMPLATE \"\"\"{{{{ if .System }}}}<|start_header_id|>system<|end_header_id|>

{{{{ .System }}}}<|eot_id|>{{{{ end }}}}{{{{ if .Prompt }}}}<|start_header_id|>user<|end_header_id|>

{{{{ .Prompt }}}}<|eot_id|>{{{{ end }}}}<|start_header_id|>assistant<|end_header_id|>

\"\"\"
PARAMETER stop "<|eot_id|>"
"""

    modelfile_path.write_text(modelfile_content, encoding="utf-8")

    try:
        # Check if ollama is installed
        subprocess.run(
            ["ollama", "create", model_name, "-f", str(modelfile_path)],
            check=True,
            capture_output=True,
            text=True,
        )
    except FileNotFoundError:
        raise RuntimeError("Ollama CLI not found. Please install Ollama first.")
    except subprocess.CalledProcessError as e:
        raise RuntimeError(f"Ollama deployment failed: {e.stderr}")
